version: 1.7.0.{build}
assembly_info:
  patch: true
  file: '**\SharedAssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
    - rd /s /q C:\Tools\nuget
    - md C:\Tools\nuget
    - ps: (New-Object Net.WebClient).DownloadFile('https://dist.nuget.org/win-x86-commandline/v3.4.2-rc/nuget.exe', 'C:\Tools\nuget\nuget.exe')

before_build:
- cmd: nuget restore Glass.sln
build:
  project: Glass.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal